"""initial schema

The whole of PRD §4 in one migration: households, members, pantry, menu, and
the two chat tables. The chat tables have no endpoints until phase 5 — they
land now so the schema is migrated once rather than twice, and so the
household scoping is uniform from the first row ever written.

Every tenant-scoped table carries household_id, and the one unique constraint
that could span tenants (uq_menu_slot) includes it.

Revision ID: 5350b580fb39
Revises:
Create Date: 2026-08-10 13:31:37.670277
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5350b580fb39'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='America/New_York', nullable=False),
    sa.Column('week_starts_on', sa.String(length=10), server_default='monday', nullable=False),
    sa.Column('mealie_group_id', sa.String(length=64), nullable=True),
    sa.Column('mealie_shopping_list_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("week_starts_on IN ('monday','tuesday','wednesday','thursday','friday','saturday','sunday')", name='ck_households_week_start'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('initials', sa.String(length=4), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=10), server_default='adult', nullable=False),
    sa.Column('can_use_basil', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('plan_reminder_day', sa.String(length=10), nullable=True),
    sa.Column('plan_reminder_hour', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("plan_reminder_day IS NULL OR plan_reminder_day IN ('monday','tuesday','wednesday','thursday','friday','saturday','sunday')", name='ck_members_reminder_day'),
    sa.CheckConstraint("role IN ('adult','child')", name='ck_members_role'),
    sa.CheckConstraint('plan_reminder_hour IS NULL OR (plan_reminder_hour BETWEEN 0 AND 23)', name='ck_members_reminder_hour'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_token_hash'), ['token_hash'], unique=True)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant')", name='ck_chat_role'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('idx_chat_conv', ['household_id', 'conversation_id', 'created_at'], unique=False)

    op.create_table('chat_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_usage', schema=None) as batch_op:
        batch_op.create_index('idx_chat_usage_member', ['household_id', 'member_id', 'created_at'], unique=False)

    op.create_table('menu_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('meal_slot', sa.String(length=20), server_default='dinner', nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('mealie_recipe_id', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cooked_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("(entry_type = 'recipe' AND mealie_recipe_id IS NOT NULL) OR (entry_type = 'freeform' AND mealie_recipe_id IS NULL)", name='ck_menu_type_matches_recipe_id'),
    sa.CheckConstraint("day_of_week IN ('monday','tuesday','wednesday','thursday','friday','saturday','sunday')", name='ck_menu_day'),
    sa.CheckConstraint("entry_type IN ('recipe','freeform')", name='ck_menu_entry_type'),
    sa.CheckConstraint('servings IS NULL OR servings > 0', name='ck_menu_servings_positive'),
    sa.ForeignKeyConstraint(['cooked_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'week_start', 'day_of_week', 'meal_slot', name='uq_menu_slot')
    )
    with op.batch_alter_table('menu_entries', schema=None) as batch_op:
        batch_op.create_index('idx_menu_week', ['household_id', 'week_start'], unique=False)

    op.create_table('pantry_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.String(length=60), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=10), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("location IN ('fridge','pantry','freezer')", name='ck_pantry_location'),
    sa.ForeignKeyConstraint(['added_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pantry_items', schema=None) as batch_op:
        batch_op.create_index('idx_pantry_active', ['household_id', 'location', 'used_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry_items', schema=None) as batch_op:
        batch_op.drop_index('idx_pantry_active')

    op.drop_table('pantry_items')
    with op.batch_alter_table('menu_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_menu_week')

    op.drop_table('menu_entries')
    with op.batch_alter_table('chat_usage', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_usage_member')

    op.drop_table('chat_usage')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_conv')

    op.drop_table('chat_messages')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_token_hash'))
        batch_op.drop_index(batch_op.f('ix_members_household_id'))

    op.drop_table('members')
    op.drop_table('households')
    # ### end Alembic commands ###
